# Use a imagem oficial do Node.js como base
FROM node:16

# Crie e defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o package.json e package-lock.json (se houver) para o diretório de trabalho
COPY ./package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie todos os arquivos do diretório local para o diretório de trabalho no container
COPY . .

# Exponha a porta 8080
EXPOSE 8080

# Defina o comando para iniciar a aplicação Vue
CMD ["npm", "run", "serve"]
